### ISSUE TITLE
line height playlist card

### ISSUE THREAD

**Issue by koeenm** [wingsvn/the-web-is-for-everyone-interactive-functionality#3]
de line height op de kaartjes in je playlist carousel is vrij groot, het zal makkelijker te lezen zijn als deze tekst wat minder ver van elkaar zit

![image](https://github.com/wingsvn/the-web-is-for-everyone-interactive-functionality/assets/144009715/25f08180-227c-4aa3-953d-457ebbdeeeb2)

**Comment by wingsvn** [comment]
Ik heb de line-height aangepast naar een vaste hoogte, bedankt! 
``` 
h3 {
    line-height: 1.4;
}
```
